### ISSUE TITLE
failed to install Hugo-obsidian

### ISSUE THREAD

**Issue by lb19940508** [jackyzha0/hugo-obsidian#1]
I tried to install Hugo-obsidan, but it seemed that I didn't install it 

```bash
$ go install github.com/jackyzha0/hugo-obsidian
go install: version is required when current directory is not in a module
	Try 'go install github.com/jackyzha0/hugo-obsidian@latest' to install the latest version
MacBook-Pro:quartz leo$ go install github.com/jackyzha0/hugo-obsidian@latest
MacBook-Pro:quartz leo$ hugo-obsidian -input=content -output=data
-bash: hugo-obsidian: command not found
```

Would you please help out?
Thanks

Best regards

**Comment by jackyzha0** [comment]
![image](https://user-images.githubusercontent.com/23178940/130301200-81da13cd-063e-4373-ab03-1e68bf955f34.png)

have you tried fixing your GOPATH?

**Comment by lb19940508** [comment]
> have you tried fixing your GOPATH?
I saw this post in the troubleshooting part, and I tried to find the file named `.bash_profile` but failed.
I'm not sure whether I had a correct understanding here.
I considered the `.bash_profile` above as a file that could be edited, so I tried this in `go` directory
```bash
liubodeMacBook-Pro:~ leo$ pwd
/Users/leo
liubodeMacBook-Pro:~ leo$ cd go
liubodeMacBook-Pro:go leo$ pwd
/Users/leo/go
liubodeMacBook-Pro:go leo$ cat ~/.bash_profile
cat: /Users/leo/.bash_profile: No such file or directory
```
It show's that there's no such file, then I also attempted to read the file in its sub-directory `bin`
```bash
liubodeMacBook-Pro:bin leo$ ls
hugo-obsidian
liubodeMacBook-Pro:bin leo$ pwd
/Users/leo/go/bin
liubodeMacBook-Pro:bin leo$ cat ~/.bash_profile
cat: /Users/leo/.bash_profile: No such file or directory

```
I didn't find the file `.bash_profile` either. So, I thought I should find those file with `GOPATH` in it, but only find some files in the `testdata` directory under `go` directory
![image](https://user-images.githubusercontent.com/34482511/130308516-174311d4-0c94-4b53-9ade-aa7d9ae861d6.png)

I'm new to `go` and only have limited coding knowledge, thus there maybe a misunderstanding here, would please help me figure it out where is the file `.bash_profile` and those codes below should be put into
```bash
export GOPATH=/Users/$USER/go
export PATH=$GOPATH/bin:$PATH
```

Thanks.

Best regards

**Comment by jackyzha0** [comment]
You can create the file manually

**Comment by lb19940508** [comment]
> You can create the file manually

Thanks, it works.
So the problem here is I didn't manually create the `.bash_profile` and reinstall hugo-obsidian again in the same terminal, in case anyone who come across the same snag.
Regards.
