### ISSUE TITLE
[Bug] Fail to render Hugo sites on Windows 11

### ISSUE THREAD

**Issue by lynn-gu** [jackyzha0/hugo-obsidian#12]
Cannot render local website by running `hugo-obsidian -input=content -output=data -index -root=.` then `hugo server`. Returns
```plaintext
ERROR 2022/02/12 10:31:26 render of "page" failed: execute of template failed: template: _default/single.html:34:6: executing "_default/single.html" at <partial "footer.html" .>: error calling partial: execute of template failed: template: partials/footer.html:4:10: executing "partials/footer.html" at <partial "backlinks.html" .>: error calling partial: "..\layouts\partials\backlinks.html:12:30": execute of template failed: template: partials/backlinks.html:12:30: executing "partials/backlinks.html" at <index (index $contentTable .) "title">: error calling index: index of untyped nil
```

The problem is caused by Line 12 in `layouts\partials\backlinks.html`:
```html
<a href="{{.}}">{{index (index $contentTable .) "title"}}</a>
```

This error can be reproduced on Windows 11 and Golang version 1.17.6 Windows/AMD 64.

**Comment by shinyben** [comment]
I am able to reproduce this on Windows 11 Golang 1.17.6 by running `hugo-obsidian -input=content -output=assets/indices -index -root=.` twice in a row and also when mass renaming files (which also occurs when a folder containing many files changes name). I ran `go install github.com/jackyzha0/hugo-obsidian@latest` earlier today
