### ISSUE TITLE
[Feature Request] Grey out broken links

### ISSUE THREAD

**Issue by shinyben** [jackyzha0/hugo-obsidian#17]
Obsidian Publish, when serving a note that contains links to non-public notes, shows the link doesn't exist by greying it out and making it not redirect when clicked. Quartz makes the link look like an existent link, but when clicked the link 404's, which is less clean.

In the case in which a vault has a large proportion of links to non-public notes (either because of only wanting to serve a portion of the true vault or by using links as note ToDos) this makes the vault navigable only if you can put up with a significant proportion of your clicks being 404'd.

**Comment by jackyzha0** [comment]
Fixed in https://github.com/jackyzha0/quartz/commit/c51573efa98de6b5b5e79fb60b49f31daca70527 :))
