### ISSUE TITLE
Links to domain .md could not be recognized correctly

### ISSUE THREAD

**Issue by lb19940508** [jackyzha0/hugo-obsidian#2]
- I tried to add a markdown link `[Obsidian](https://obsidian.md)` on the website using quartz. However, when click the link on the website, it forward the address to` https://obsidian/`, an address without `.md`.
- I think maybe quartz recognize the domian `.md` as a markdown file, thus forward it to a wrong address.
- I also changed the `https://obsidian.md` to `https://www.obsidian.md`, but it's the same result without `.md`
- I tried this on chrome browser both on android and macOS.
- Here is what the image of what has been rendered:
![image](https://user-images.githubusercontent.com/34482511/130310360-625bee81-fdb8-4f3f-ac9e-71d77f2b8a65.png)

Please check it out,
Regards.

This issue is recommended to be filed here from https://github.com/jackyzha0/quartz/issues/11#issue-975445797

**Comment by jackyzha0** [comment]
can you try adding a trailing slash `/` to the URL? otherwise, Quartz will assume it has a .md ending.

Try changing `[Obsidian](https://obsidian.md)` to `[Obsidian](https://obsidian.md/)`

**Comment by lb19940508** [comment]
> can you try adding a trailing slash `/` to the URL? otherwise, Quartz will assume it has a .md ending.
> 
> Try changing `[Obsidian](https://obsidian.md)` to `[Obsidian](https://obsidian.md/)`

- Problem solved. Thanks a lot!

Regards.
