### ISSUE TITLE
[BUG]Multiple nodes for files with spaces in their name

### ISSUE THREAD

**Issue by Naevyr** [jackyzha0/hugo-obsidian#6]
Title is self explanatory. Problem doesn't occur without spaces.

Here's my attempt at understanding the problem, I will try tomorrow or in the next days to see if I can confirm and maybe fix it.

For the linkIndex.yaml generation, if I understand correctly, 
the program will use the file name+path for the _source_ , and the link inside the page for _target_ .
With markdown styled links obsidian uses encoded urls (' ' -> '%20'). 
This creates a name difference between the target("a%20b") and the source("a b"), resulting in 2 different nodes pointing at the same file.

**Comment by jackyzha0** [comment]
Can you replicate this? Found another bug while trying to fix this (not parsing multiple links in the same line) but it seems that Hugo just parses ' ' as '-'.

**Comment by Naevyr** [comment]
> Can you replicate this? Found another bug while trying to fix this (not parsing multiple links in the same line) but it seems that Hugo just parses ' ' as '-'.

Yes, one of the two nodes generated has '-', the other one is labelled correctly. I guessed it was the encoded one bugging out, so I didn't bother to mention it.
